#ifndef RZ_RAKNET_IDENTIFIERS_H
#define RZ_RAKNET_IDENTIFIERS_H

enum MessageID {
    ID_UNCONNECTED_PING = 0x01,
    ID_OPEN_CONNECTION_REQUEST_1 = 0x05,
    ID_OPEN_CONNECTION_REPLY_1 = 0x06,
    ID_OPEN_CONNECTION_REQUEST_2 = 0x07,
    ID_OPEN_CONNECTION_REPLY_2 = 0x08,
    ID_CONNECTION_REQUEST = 0x09,
    ID_CONNECTION_REQUEST_ACCEPTED = 0x10,
    ID_TIMESTAMP = 0x1b,
    ID_UNCONNECTED_PONG = 0x1c
};

#endif // RZ_RAKNET_IDENTIFIERS_H